#!/bin/bash

output_file="aggregated_code.txt"
> "$output_file"

find . \( -path '*/node_modules/*' -o -path '*/.*' \) -prune -o -type f ! -name 'package-lock.json' \( \
    -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \
    -o -name "*.json" -o -name "*.md" -o -name "*.html" \
    -o -name ".babelrc" \
\) -print | while read -r file; do
    echo "=== $file ===" >> "$output_file"
    cat "$file" >> "$output_file"
    echo -e "\n" >> "$output_file"
done